### ISSUE TITLE
Implement 'create named-graph' command 

### ISSUE THREAD

**Issue by adpadilla** [datacequia/go-dogg3rz#20]
Need to be able to create a named graph within a dataset. The name should be a unique name/IRI within the dataset.

The syntax should be as follows:

**dogg3rz create named-graph|ng _NAME_ dataset|ds _DATASET_ [parent _NAMED_GRAPH_]** 

where _NAME_ is the name given to the new named graph (this and other names used in dogg3rz should follow some character set restrictions TBD)
where _DATASET_ is the name of the dataset container for the new named graph

where **parent**   is an optional subcommand that determines the parent named graph container for the new named graph. 

Should error with NotFound if _DATASET_ or _NAMED_GRAPH_ do not exist as datasets or named graphs respectively.
Should error with AlreadyExists if _NAME_ already exists as a named-graph (it may need to be researched whether or not any IRI with the same name is allowed in spec such as a node name ).

**Comment by bhallamp** [comment]
should this be create named graph or insert named graph?

**Comment by adpadilla** [comment]
Good question. I am trying to use SQL like terminology when referring to creation of resources. In this case, named graphs are a structural resource (container) and so i put them in the 'create' bucket. nodes are data resources which are not containers ( i.e don't define the structure of json-ld doc) so insert is used. the only nodes which are exception are types ( create type) per for same reason.

**Comment by adpadilla** [comment]
works on my end. closing
